connections:
  aws: ''
desc: ''
name: '"foundational_security_elbv2"'
steps:
- desc: example description delete afterwards
  text: '#1 Application Load Balancer should be configured to redirect all HTTP requests
    to HTTPS - Not implemented'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: ''
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
