connections:
  aws: ''
desc: ''
name: '"foundational_security_ec2"'
steps:
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S3
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S4
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S3.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S5
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S6
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S5.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S7
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S8
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S7.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S9
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S10
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S9.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S11
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S12
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S11.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S13
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S14
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S13.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S15
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S16
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S15.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#10 Amazon EC2 should be configured to use VPC endpoints'
- action: core.sql
  desc: Description
  id: S17
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ vpc_id not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when vpc_id\
      \ not in (\n      select\n        vpc_id\n      from\n        aws_vpc_endpoint\n\
      \      where\n        service_name like 'com.amazonaws.' || region || '.ec2'\n\
      \    ) then title || ' not configured to use VPC endpoints.'\n    else title\
      \ || ' configured to use VPC endpoints.'\n  end as reason,\n  -- Additional\
      \ Dimensions\n  region,\n  account_id\nfrom\n  aws_vpc;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S18
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S17.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
