connections:
  aws: ''
desc: ''
name: '"foundational_security_autoscaling"'
steps:
- desc: example description delete afterwards
  text: '#1 Auto Scaling groups associated with a load balancer should use load balancer
    health checks'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: " \n select\n  -- Required Columns\n  autoscaling_group_arn as resource,\n\
      \  case\n    when load_balancer_names is null and target_group_arns is null\
      \ then 'alarm'\n    when health_check_type != 'ELB' then 'alarm'\n    else 'ok'\n\
      \  end as status,\n  case\n    when load_balancer_names is null and target_group_arns\
      \ is null then title || ' not associated with a load balancer.'\n    when health_check_type\
      \ != 'ELB' then title || ' does not use ELB health check.'\n    else title ||\
      \ ' uses ELB health check.'\n  end as reason,\n  -- Additional Dimensions\n\
      \  region,\n  account_id\nfrom\n  aws_ec2_autoscaling_group;\n"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
