connections:
  aws: ''
desc: ''
name: '"foundational_security_cloudfront"'
steps:
- desc: example description delete afterwards
  text: '#4 CloudFront distributions should have origin failover configured'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ json_extract(origin_groups,'$.Items') is not null then 'ok'\n    else 'alarm'\n\
      \  end as status,\n  case\n    when json_extract(origin_groups,'$.Items') is\
      \ not null then title || ' origin group is configured.'\n    else title || '\
      \ origin group not configured.'\n  end as reason,\n  -- Additional Dimensions\n\
      \  region,\n  account_id\nfrom\n  aws_cloudfront_distribution;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#4 CloudFront distributions should have origin failover configured'
- action: core.sql
  desc: Description
  id: S3
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ json_extract(origin_groups,'$.Items') is not null then 'ok'\n    else 'alarm'\n\
      \  end as status,\n  case\n    when json_extract(origin_groups,'$.Items') is\
      \ not null then title || ' origin group is configured.'\n    else title || '\
      \ origin group not configured.'\n  end as reason,\n  -- Additional Dimensions\n\
      \  region,\n  account_id\nfrom\n  aws_cloudfront_distribution;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S4
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S3.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#4 CloudFront distributions should have origin failover configured'
- action: core.sql
  desc: Description
  id: S5
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ json_extract(origin_groups,'$.Items') is not null then 'ok'\n    else 'alarm'\n\
      \  end as status,\n  case\n    when json_extract(origin_groups,'$.Items') is\
      \ not null then title || ' origin group is configured.'\n    else title || '\
      \ origin group not configured.'\n  end as reason,\n  -- Additional Dimensions\n\
      \  region,\n  account_id\nfrom\n  aws_cloudfront_distribution;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S6
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S5.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#4 CloudFront distributions should have origin failover configured'
- action: core.sql
  desc: Description
  id: S7
  inputs:
    sql: " \n select\n  -- Required Columns\n  arn as resource,\n  case\n    when\
      \ json_extract(origin_groups,'$.Items') is not null then 'ok'\n    else 'alarm'\n\
      \  end as status,\n  case\n    when json_extract(origin_groups,'$.Items') is\
      \ not null then title || ' origin group is configured.'\n    else title || '\
      \ origin group not configured.'\n  end as reason,\n  -- Additional Dimensions\n\
      \  region,\n  account_id\nfrom\n  aws_cloudfront_distribution;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S8
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S7.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
