connections:
  aws: ''
desc: ''
name: '"foundational_security_apigateway"'
steps:
- desc: example description delete afterwards
  text: '#2 API Gateway REST API stages should be configured to use SSL certificates
    for backend authentication'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: " \n select\n  -- Required Columns\n  'arn:' || partition || ':apigateway:'\
      \ || region || '::/apis/' || rest_api_id || '/stages/' as resource,\n  case\n\
      \    when client_certificate_id is null then 'alarm'\n    else 'ok'\n  end as\
      \ status,\n  case\n    when client_certificate_id is null then title || ' not\
      \ uses SSL certificate.'\n    else title || ' uses SSL certificate.'\n  end\
      \ as reason,\n  -- Additional Dimensions\n  region,\n  account_id\nfrom\n  aws_api_gateway_stage;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
- desc: example description delete afterwards
  text: '#2 API Gateway REST API stages should be configured to use SSL certificates
    for backend authentication'
- action: core.sql
  desc: Description
  id: S3
  inputs:
    sql: " \n select\n  -- Required Columns\n  'arn:' || partition || ':apigateway:'\
      \ || region || '::/apis/' || rest_api_id || '/stages/' as resource,\n  case\n\
      \    when client_certificate_id is null then 'alarm'\n    else 'ok'\n  end as\
      \ status,\n  case\n    when client_certificate_id is null then title || ' not\
      \ uses SSL certificate.'\n    else title || ' uses SSL certificate.'\n  end\
      \ as reason,\n  -- Additional Dimensions\n  region,\n  account_id\nfrom\n  aws_api_gateway_stage;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S4
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S3.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
