connections:
  aws: ''
desc: ''
name: '"foundational_security_elbv2"'
steps:
- desc: example description delete afterwards
  text: '#1 Application Load Balancer should be configured to redirect all HTTP requests
    to HTTPS'
- action: core.sql
  desc: Description
  id: S1
  inputs:
    sql: " \n with detailed_listeners as (\n  select\n    arn,\n    load_balancer_arn,\n\
      \    protocol\n  from\n    aws_ec2_load_balancer_listener,\n    json_each(default_actions)\
      \ as ac\n  where\n    split_part(arn,'/',2) = 'app'\n    and protocol = 'HTTP'\n\
      \    and json_extract(ac.value,'$.Type') = 'redirect'\n    and json_extract(ac.value,'$.RedirectConfig.Protocol')\
      \ = 'HTTPS'\n)\nselect\n  -- Required Columns\n  a.arn as resource,\n  case\n\
      \    when b.load_balancer_arn is null then 'alarm'\n    else 'ok'\n  end as\
      \ status,\n   case\n    when b.load_balancer_arn is not null then  a.title ||\
      \ ' associated with HTTP redirection.'\n    else a.title || ' not associated\
      \ with HTTP redirection.'\n  end as reason,\n  -- Additional Dimensions\n  a.region,\n\
      \  a.account_id\nfrom\n  aws_ec2_application_load_balancer a\n  left join detailed_listeners\
      \ b on a.arn = b.load_balancer_arn;"
  name: Perform the query
- action: slack.SendFile
  connections:
    slack: slack_connection
  desc: Description
  id: S2
  inputs:
    Channel: demo
    Content: '{{table_to_csv(steps.S1.output)}}'
    File name: ''
    File type: csv
  name: Send report to Slack
tags: []
type: Flow
