name: ""
type: Flow
tags: []
desc: ""
inputs:
  send_notif:
    display_name: Send Slack Notification
    type: checkbox
    required: true
    default: true
connections:
  aws: "aws_connection"
steps: []