steps:
  - desc: example description delete afterwards
    text: "# "
  - action: core.sql
    id: S1
    name: Perform the query
    desc: Description
    inputs:
      sql: |-
        query
  - action: core.python
    id: S2
    name: Format Result
    desc: Description
    inputs:
      code: >-
        from dotmap import DotMap
        
        import json

        filtered_on_alarm = [x for x in context.steps.S1.output.rows if ( x[context.steps.S1.output.columns.index('status')] == 'alarm' )]


        check = DotMap()


        check.isAlarm = len(filtered_on_alarm) > 0

        check.details = context.steps.S1.output.rows

        check.name = "ControlName"

        check.severity = "DefaultSeverity"


        print(json.dumps(check.toDict()))